Added ASCII logos
meshtastic/meshtastic-design pull request #26
Opened 2024-10-30 19:39 UTC by noon92

I swear, they look better in standard terminal fonts! Github's default font is not ideal for this...

2024-10-30 20:43 UTC, caveman99 approved these changes

2024-10-30 20:46 UTC, caveman99 commented
Please don't merge this just now, we need to change something in the repo before we can.

2024-12-25 15:41 UTC, noon92 commented
Any chance we can have this merged, or are there any requests for changes?

2024-12-25 15:45 UTC, garthvh requested changes
Other than the mini, these are the m logo and would require a trademark grant to use

2024-12-25 17:50 UTC, noon92 commented
Changes made.

2024-12-25 18:55 UTC, garthvh requested changes
Please remove example.png, that is not going to work.

2024-12-25 18:57 UTC, noon92 commented
Yep, missed that, thanks.

2026-04-24 17:46 UTC, closed without merging